import { Lora, Inter, Kaushan_Script } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Drawer from "@/components/Drawer";
import Cart from "@/components/Cart";
import AppWrapper from "./context/AppWrapper";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
});


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const script = Kaushan_Script({
  variable: "--font-script",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Restaurant Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${inter.variable} ${script.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppWrapper>
          <Drawer />
          <Navbar />
          <Cart />
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}