import { Lora, Inter, Kaushan_Script } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Drawer from "@/components/Drawer";
import Cart from "@/components/Cart";
import AppWrapper from "./context/AppWrapper";
import { Toaster } from "react-hot-toast";
import FooterSection from "@/components/FooterSection";
import AosInit from "@/components/AosInit";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
});


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const script = Kaushan_Script({
  variable: "--font-script",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Restaurant Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${inter.variable} ${script.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppWrapper>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 3000,
              style: {
                background: '#1e2326',
                color: '#FBE3A1',
                border: '1px solid rgba(245,190,50,0.3)',
                fontFamily: 'serif',
                fontSize: '1rem',
                letterSpacing: '0.05em',
              },
            }}
          />
          <AosInit />
          <Drawer />
          <Cart />
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
            <FooterSection />
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}